### Listar todas
GET http://localhost:8080/api/applications

### Crear una candidatura
POST http://localhost:8080/api/applications
Content-Type: application/json

{
  "company": "Apple",
  "position": "Backend Developer Junior",
  "status": "SAVED",
  "location": "Madrid",
  "workMode": "REMOTE",
  "salaryMin": 24000,
  "salaryMax": 30000,
  "offerUrl": "https://www.linkedin.com/jobs/view/123456789",
  "source": "LinkedIn",
  "appliedAt": "2026-08-24"
}

### Ver una por id
GET http://localhost:8080/api/applications/1

### Ver una que no existe
GET http://localhost:8080/api/applications/999

### Sin company
POST http://localhost:8080/api/applications
Content-Type: application/json

{
  "position": "Backend Developer Junior",
  "status": "SAVED",
  "location": "Madrid",
  "workMode": "REMOTE",
  "salaryMin": 24000,
  "salaryMax": 30000,
  "offerUrl": "https://www.linkedin.com/jobs/view/123456789",
  "source": "LinkedIn",
  "appliedAt": "2026-08-21"
}

### Salario negativo
POST http://localhost:8080/api/applications
Content-Type: application/json

{
  "company": "Accenture",
  "position": "Backend Developer Junior",
  "status": "SAVED",
  "location": "Madrid",
  "workMode": "REMOTE",
  "salaryMin": -24000,
  "salaryMax": -30000,
  "offerUrl": "https://www.linkedin.com/jobs/view/123456789",
  "source": "LinkedIn",
  "appliedAt": "2026-08-21"
}

### Put
PUT http://localhost:8080/api/applications/6
Content-Type: application/json

{
  "company": "Apple",
  "position": "Backend Developer Junior",
  "status": "SAVED",
  "location": "Madrid",
  "workMode": "REMOTE",
  "salaryMin": 3000,
  "salaryMax": 40000,
  "offerUrl": "https://www.linkedin.com/jobs/view/123456789",
  "source": "LinkedIn",
  "appliedAt": "2026-08-24"
}

### Delete borrar uno
DELETE http://localhost:8080/api/applications/3

### Token inválido
GET http://localhost:8080/api/applications
Authorization: Bearer esto-no-es-un-token

### 1. Registro
POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
  "name": "Fabian",
  "email": "fabian@jobtrack.com",
  "password": "password123"
}

### 2. Login
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "email": "fabian@jobtrack.com",
  "password": "password123"
}

### 3. Petición autenticada
GET http://localhost:8080/api/applications
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJmYWJpYW5Aam9idHJhY2suY29tIiwiaWF0IjoxNzg4MjA0NzI2LCJleHAiOjE3ODgyOTExMjZ9.3-n0XmFTGVhidzLc9u9zOfValfBVxKxlLPXklCZINMTgTGeWzGjKZRxYBelYWb_H

### Listar todas
GET http://localhost:8080/api/applications
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJmYWJpYW5Aam9idHJhY2suY29tIiwiaWF0IjoxNzg4MzUxMjU1LCJleHAiOjE3ODg0Mzc2NTV9.iyXcKsdKjLuUUIoexIIlOg6yJZTaACgSRuZdq5xlyBTOPvaeausSY1zX2EGum0Kj

### Crear
POST http://localhost:8080/api/applications
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJmYWJpYW5Aam9idHJhY2suY29tIiwiaWF0IjoxNzg4MjY5MTI2LCJleHAiOjE3ODgzNTU1MjZ9.q_UX90OLMHby7bUOsTjS7uwC8k6PeG3I89JbQuM-kDWDekY_lg7wd0jOSh6Z_MTI

{
  "company": "Telefónica",
  "position": "Java Developer",
  "location": "Madrid",
  "workMode": "HYBRID",
  "salaryMin": 26000,
  "salaryMax": 32000,
  "source": "LinkedIn"
}

### Candidatura de otro usuario
GET http://localhost:8080/api/applications/1
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJmYWJpYW5Aam9idHJhY2suY29tIiwiaWF0IjoxNzg4MjY4MjA0LCJleHAiOjE3ODgzNTQ2MDR9.vEOTPg5YLgoFqK3v2kxtijA10vYiSIN1H77MkHeoG_xA8y6fZONPsS4HlF2H3mRe