spring.application.name=jobtrack-api
spring.jpa.open-in-view=false

# Conexion a PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/jobtrack
spring.datasource.username=jobtrack_user
spring.datasource.password=jobtrack_pass

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs